### ISSUE TITLE
Failed: Installing Cityhash with Ruby2.1 win386 

### ISSUE THREAD

**Issue by HatemMS2012** [nashby/cityhash#28]
Hi,

I am trying to install cityhash using ruby 2.1 under win-i386 by typing the follwing in the command line:

gem install cityhash

and I am getting the follwing error message:

C:/Ruby21/bin/ruby.exe extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
generating cityhash-i386-mingw32.def
compiling city.cc
city.cc:64:22: fatal error: byteswap.h: No such file or directory
compilation terminated.
make: **\* [city.o] Error 1

make failed, exit code 2

I would appreciate any help.

Best,

**Comment by TrangPham** [comment]
I am also having the same error

Here is my output:
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    C:/Ruby22-x64/bin/ruby.exe -r ./siteconf20150322-3768-79bsgu.rb extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
generating cityhash-x64-mingw32.def
compiling city.cc
city.cc:64:22: fatal error: byteswap.h: No such file or directory
compilation terminated.
make: *** [city.o] Error 1

make failed, exit code 2

Gem files will remain installed in C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/cityhash-0.8.1 for inspection.
Results logged to C:/Ruby22-x64/lib/ruby/gems/2.2.0/extensions/x64-mingw32/2.2.0/cityhash-0.8.1/gem_make.out
An error occurred while installing cityhash (0.8.1), and Bundler cannot
continue.
Make sure that `gem install cityhash -v '0.8.1'` succeeds before bundling.
```

**Comment by nashby** [comment]
@TrangPham @HatemMS2012 hey! Sorry about that. I don't really use Windows for ruby development so can't really help. But pull requests are welcome! So if you wanna try to fix it just give it a try. I'm totally here to help you.
