### ISSUE TITLE
Issue installing cityhash in ruby-1.9.3-p392

### ISSUE THREAD

**Issue by yashwinkumar** [nashby/cityhash#29]
Building native extensions.  This could take a while...
ERROR:  Error installing cityhash:
    ERROR: Failed to build gem native extension.

```
/usr/local/rvm/rubies/ruby-1.9.3-p392/bin/ruby extconf.rb
```

creating Makefile

make
compiling city.cc
cc1plus: warning: command line option ‘-Wdeclaration-after-statement’ is valid for C/ObjC but not for C++ [enabled by default]
cc1plus: warning: command line option ‘-Wimplicit-function-declaration’ is valid for C/ObjC but not for C++ [enabled by default]
city.cc: In function ‘uint32 Hash32Len0to4(const char_, size_t)’:
city.cc:145:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
city.cc: In function ‘void CityHashCrc256Long(const char_, size_t, uint32, uint64_)’:
city.cc:531:5: error: ‘_mm_crc32_u64’ was not declared in this scope
city.cc:540:5: error: ‘_mm_crc32_u64’ was not declared in this scope
city.cc:550:5: error: ‘_mm_crc32_u64’ was not declared in this scope
make: *_\* [city.o] Error 1

Gem files will remain installed in /usr/local/rvm/gems/ruby-1.9.3-p392/gems/cityhash-0.8.1 for inspection.
Results logged to /usr/local/rvm/gems/ruby-1.9.3-p392/gems/cityhash-0.8.1/ext/cityhash/gem_make.out

*cat /proc/cpuinfo
processor   : 0
vendor_id   : GenuineIntel
cpu family  : 6
model       : 45
model name  : Intel(R) Xeon(R) CPU E5-2630L 0 @ 2.00GHz
stepping    : 7
microcode   : 0x70d
cpu MHz     : 2000.066
cache size  : 15360 KB
physical id : 0
siblings    : 8
core id     : 1
cpu cores   : 1
apicid      : 3
initial apicid  : 3
fdiv_bug    : no
f00f_bug    : no
coma_bug    : no
fpu     : yes
fpu_exception   : yes
cpuid level : 13
wp      : yes
flags       : fpu de tsc msr pae cx8 apic cmov pat clflush mmx fxsr sse sse2 ss ht nx constant_tsc nonstop_tsc pni pclmulqdq ssse3 sse4_1 sse4_2 popcnt tsc_deadline_timer aes hypervisor ida arat epb pln pts dtherm
bugs        :
bogomips    : 4001.80
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

processor   : 1
vendor_id   : GenuineIntel
cpu family  : 6
model       : 45
model name  : Intel(R) Xeon(R) CPU E5-2630L 0 @ 2.00GHz
stepping    : 7
microcode   : 0x70d
cpu MHz     : 2000.066
cache size  : 15360 KB
physical id : 0
siblings    : 8
core id     : 1
cpu cores   : 1
apicid      : 3
initial apicid  : 3
fdiv_bug    : no
f00f_bug    : no
coma_bug    : no
fpu     : yes
fpu_exception   : yes
cpuid level : 13
wp      : yes
flags       : fpu de tsc msr pae cx8 apic cmov pat clflush mmx fxsr sse sse2 ss ht nx constant_tsc nonstop_tsc pni pclmulqdq ssse3 sse4_1 sse4_2 popcnt tsc_deadline_timer aes hypervisor ida arat epb pln pts dtherm
bugs        :
bogomips    : 4001.80
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

processor   : 2
vendor_id   : GenuineIntel
cpu family  : 6
model       : 45
model name  : Intel(R) Xeon(R) CPU E5-2630L 0 @ 2.00GHz
stepping    : 7
microcode   : 0x70d
cpu MHz     : 2000.066
cache size  : 15360 KB
physical id : 0
siblings    : 8
core id     : 1
cpu cores   : 1
apicid      : 3
initial apicid  : 3
fdiv_bug    : no
f00f_bug    : no
coma_bug    : no
fpu     : yes
fpu_exception   : yes
cpuid level : 13
wp      : yes
flags       : fpu de tsc msr pae cx8 apic cmov pat clflush mmx fxsr sse sse2 ss ht nx constant_tsc nonstop_tsc pni pclmulqdq ssse3 sse4_1 sse4_2 popcnt tsc_deadline_timer aes hypervisor ida arat epb pln pts dtherm
bugs        :
bogomips    : 4001.80
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

processor   : 3
vendor_id   : GenuineIntel
cpu family  : 6
model       : 45
model name  : Intel(R) Xeon(R) CPU E5-2630L 0 @ 2.00GHz
stepping    : 7
microcode   : 0x70d
cpu MHz     : 2000.066
cache size  : 15360 KB
physical id : 0
siblings    : 8
core id     : 1
cpu cores   : 1
apicid      : 3
initial apicid  : 3
fdiv_bug    : no
f00f_bug    : no
coma_bug    : no
fpu     : yes
fpu_exception   : yes
cpuid level : 13
wp      : yes
flags       : fpu de tsc msr pae cx8 apic cmov pat clflush mmx fxsr sse sse2 ss ht nx constant_tsc nonstop_tsc pni pclmulqdq ssse3 sse4_1 sse4_2 popcnt tsc_deadline_timer aes hypervisor ida arat epb pln pts dtherm
bugs        :
bogomips    : 4001.80
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

processor   : 4
vendor_id   : GenuineIntel
cpu family  : 6
model       : 45
model name  : Intel(R) Xeon(R) CPU E5-2630L 0 @ 2.00GHz
stepping    : 7
microcode   : 0x70d
cpu MHz     : 2000.066
cache size  : 15360 KB
physical id : 0
siblings    : 8
core id     : 1
cpu cores   : 1
apicid      : 3
initial apicid  : 3
fdiv_bug    : no
f00f_bug    : no
coma_bug    : no
fpu     : yes
fpu_exception   : yes
cpuid level : 13
wp      : yes
flags       : fpu de tsc msr pae cx8 apic cmov pat clflush mmx fxsr sse sse2 ss ht nx constant_tsc nonstop_tsc pni pclmulqdq ssse3 sse4_1 sse4_2 popcnt tsc_deadline_timer aes hypervisor ida arat epb pln pts dtherm
bugs        :
bogomips    : 4001.80
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

processor   : 5
vendor_id   : GenuineIntel
cpu family  : 6
model       : 45
model name  : Intel(R) Xeon(R) CPU E5-2630L 0 @ 2.00GHz
stepping    : 7
microcode   : 0x70d
cpu MHz     : 2000.066
cache size  : 15360 KB
physical id : 0
siblings    : 8
core id     : 1
cpu cores   : 1
apicid      : 3
initial apicid  : 3
fdiv_bug    : no
f00f_bug    : no
coma_bug    : no
fpu     : yes
fpu_exception   : yes
cpuid level : 13
wp      : yes
flags       : fpu de tsc msr pae cx8 apic cmov pat clflush mmx fxsr sse sse2 ss ht nx constant_tsc nonstop_tsc pni pclmulqdq ssse3 sse4_1 sse4_2 popcnt tsc_deadline_timer aes hypervisor ida arat epb pln pts dtherm
bugs        :
bogomips    : 4001.80
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

processor   : 6
vendor_id   : GenuineIntel
cpu family  : 6
model       : 45
model name  : Intel(R) Xeon(R) CPU E5-2630L 0 @ 2.00GHz
stepping    : 7
microcode   : 0x70d
cpu MHz     : 2000.066
cache size  : 15360 KB
physical id : 0
siblings    : 8
core id     : 1
cpu cores   : 1
apicid      : 3
initial apicid  : 3
fdiv_bug    : no
f00f_bug    : no
coma_bug    : no
fpu     : yes
fpu_exception   : yes
cpuid level : 13
wp      : yes
flags       : fpu de tsc msr pae cx8 apic cmov pat clflush mmx fxsr sse sse2 ss ht nx constant_tsc nonstop_tsc pni pclmulqdq ssse3 sse4_1 sse4_2 popcnt tsc_deadline_timer aes hypervisor ida arat epb pln pts dtherm
bugs        :
bogomips    : 4001.80
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

processor   : 7
vendor_id   : GenuineIntel
cpu family  : 6
model       : 45
model name  : Intel(R) Xeon(R) CPU E5-2630L 0 @ 2.00GHz
stepping    : 7
microcode   : 0x70d
cpu MHz     : 2000.066
cache size  : 15360 KB
physical id : 0
siblings    : 8
core id     : 1
cpu cores   : 1
apicid      : 3
initial apicid  : 3
fdiv_bug    : no
f00f_bug    : no
coma_bug    : no
fpu     : yes
fpu_exception   : yes
cpuid level : 13
wp      : yes
flags       : fpu de tsc msr pae cx8 apic cmov pat clflush mmx fxsr sse sse2 ss ht nx constant_tsc nonstop_tsc pni pclmulqdq ssse3 sse4_1 sse4_2 popcnt tsc_deadline_timer aes hypervisor ida arat epb pln pts dtherm
bugs        :
bogomips    : 4001.80
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:

**Comment by nashby** [comment]
@yashwinkumar hey, thanks for reporting it! Yeah, it's been 2 years, sorry. I just released `0.9.0` version that should compile without CRC methods. Please give it a try!
